---
title: "interactive-mini1"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(maps)
library(viridis)
library(janitor) # r tip of day??
library(leaflet)
library(htmltools)
library(glue)
library(sf)
#data for proj
death_data <- read_csv("~/Documents/SDS-264/Data/death.csv")

#data for map
us_states <- map_data("state")
head(us_states)

#sf 
states <- read_sf("https://rstudio.github.io/leaflet/json/us-states.geojson")  #<2>
class(states) #<3>
states

```



```{r}
#Interactive Graph #1 with Numeric Variable

#| warning: false

#fixing up states data to match death data formatting of state names
states <- states |>
  mutate(name = str_to_lower(name))

#begin filtering and mutating death data 
int_death_data <- death_data |>
  clean_names() |>
  select(year, cause_name, state, deaths) |>
  mutate(state = str_to_lower(state)) |>
  filter(!(state %in% c("alaska", "hawaii", "united states"))) |>
  filter(cause_name %in% c("Heart disease"), year == 2017) |>
  #join death data with death data to get geometry column
  right_join(states, by = c("state" = "name")) |>
  rename(name = state) 

#geometry column not recognized, use old sf function
int_death_data2 <- sf::st_as_sf(int_death_data) |>
  filter(!(name %in% c("alaska", "hawaii", "puerto rico"))) |>
  mutate(name = str_to_title(name))

#defining color palette
pal <- colorNumeric(palette = "PuRd", domain = c(0, 65000))

#leaflet plot 
leaflet(int_death_data2) |>
  setView(-96, 37.8, 3) |>
  addTiles() |>
  addPolygons(
    weight = 1, 
    opacity = 1,
    dashArray = "3",
    fillOpacity = 0.8,
    highlightOptions = highlightOptions(
      weight = 5,
      color = "#666", 
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    popup = ~paste(name, "</br>", "Amount of deaths due to heart disease: ", deaths),
    color = ~pal(deaths)) |>
    addLegend(pal = pal, values = ~int_death_data2$deaths, 
          opacity = 0.7, title = "Number of Deaths", position = "bottomright") |>
      addControl("<h4>Deaths Due To Heart Disease in the U.S in 2017.</h4>",
               position = "topright",
               className = "map-title") |>
      addControl("<h6>Data Source: data.gov.</h6>",
               position = "bottomleft",
               className = "map-title")

```

```{r}

#Graph #4 Interactive Categorical
#| warning: false

states <- states |>
  mutate(name = str_to_lower(name))

int_cat_death_data <- death_data |>
  #cleaning col names and selecting cols
  clean_names() |>
  select(year, cause_name, state, deaths) |>
  mutate(state = str_to_lower(state)) |>
  
  #filtering cols for join
  filter(!(state %in% c("alaska", "hawaii", "united states"))) |>
  filter(cause_name %in% c("Alzheimer's disease", "Stroke"), year == 2017) |>
  
  
  #pivot so no more two rows per state - tidy data
  pivot_wider(
    names_from = cause_name,
    values_from = deaths 
  ) |>
  
  #get counts and condition for cat var 
  clean_names() |>
  count(state, stroke, alzheimers_disease) |>
  mutate(death_type = ifelse(stroke > alzheimers_disease, "Stroke", "Alzheimer's")) |>
  
  #right join to get states data
  right_join(states, by = c("state" = "name")) |>
  rename(name = state) 


#fixes  error about not having my geometry column recognized
int_cat_death_data2 <- sf::st_as_sf(int_cat_death_data) |>
  filter(!(name %in% c("alaska", "hawaii", "puerto rico"))) |>
  mutate(name = str_to_title(name))

pal <- colorFactor("PRGn", int_cat_death_data2$death_type)

leaflet(int_cat_death_data2) |>
  setView(-95, 37.8, 3) |>
  addTiles() |>
  addPolygons(
    weight = 1, 
    opacity = 1,
    dashArray = "3",
    fillOpacity = 0.8,
    highlightOptions = highlightOptions(
      weight = 5,
      color = "#666", # state outline darkness
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    color = ~pal(int_cat_death_data2$death_type),
    popup = ~paste(name, "</br>", "Cause of Death: ", death_type)) |>
    addLegend(pal = pal, values = ~int_cat_death_data2$death_type, 
          opacity = 0.7, title = "Cause of Deaths" , position = "bottomright") |>
    addControl("<h4>Greater Cause of Deaths Between Stroke or Alzheimer's in the U.S.</h4>",
               position = "topright",
               className = "map-title") |>
    addControl("<h6>Data Source: data.gov.</h6>",
               position = "bottomleft",
               className = "map-title")
```
