---
title: "mini-proj1"
format: html
editor_options: 
  chunk_output_type: console
---

#goal - chloropleth maps with two different characteristics, one numeric and one categorical
#two versions of each plot one static and one interactive
#note data source
#remember to label and alt text plot

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(maps)
library(viridis)
library(janitor) # r tip of day??
library(leaflet)
library(htmltools)
library(glue)
library(sf)
#data for proj
death_data <- read_csv("~/Documents/SDS-264/Data/death.csv")

#data for map
us_states <- map_data("state")
head(us_states)

#sf 
states <- read_sf("https://rstudio.github.io/leaflet/json/us-states.geojson")  #<2>
class(states) #<3>
states

```

```{r}
#examine state levels
unique(us_states$region)
unique(death_data$State)
```

```{r}
#Graph #1: Static with Numeric Value
num_death_data <- death_data |>
  
  #clean column names and select cols
  clean_names() |>
  select(year, cause_name, state, deaths) |>
  mutate(state = str_to_lower(state)) |>
  
  #filter -> wanted data to avoid many-to-many issue before join by shrinking dataset down
  filter(!(state %in% c("alaska", "hawaii", "united states"))) |>
  filter(cause_name %in% c("Heart disease"), year == 2017) |>
  

  #join data from us states into numerical death data set
  right_join(us_states, by = c("state" = "region")) |>
  rename(region = state) 

  #plotting data 
num_death_data |>
  ggplot(mapping = aes(x = long, y = lat,
                       group = group)) + 
  geom_polygon(aes(fill = deaths), color = "black") +
  coord_map() +  
  theme_void() +  
  scale_fill_viridis() +
  labs(   
    title = "United States Deaths By Heart Disease in 2017",
    fill = "Number of Deaths",
    caption = "Data Source: data.gov")

  


```
  

```{r}
#Graph #2: Static with categorical value

#Create data set for categorical var
cat_death_data <- death_data |>
  
  #cleaning col names and selecting cols
  clean_names() |>
  select(year, cause_name, state, deaths) |>
  mutate(state = str_to_lower(state)) |>
  
  #filtering cols for join
  filter(!(state %in% c("alaska", "hawaii", "united states"))) |>
  filter(cause_name %in% c("Alzheimer's disease", "Stroke"), year == 2017) |>
  
  
  #fixing two rows per state 
  pivot_wider(
    names_from = cause_name,
    values_from = deaths 
  ) |>
  
  #get counts and condition for cat var 
  clean_names() |>
  count(state, stroke, alzheimers_disease) |>
  mutate(death_type = ifelse(stroke > alzheimers_disease, "S", "A")) |>
  
  #Join data set to us_states
  right_join(us_states, by = c("state" = "region")) |>
  rename(region = state) 
  
  #plot
  cat_death_data |>
  ggplot(mapping = aes(x = long, y = lat,
                          group = group)) + 
  geom_polygon(aes(fill = death_type), color = "gray33", linewidth = 0.2) + 
  coord_map() + 
  theme_void() +  
  scale_fill_manual(values = c("plum4", "darkseagreen3"),
                    labels = c("Alzheimers", "Stroke")) +
  labs(fill = "Cause of Death",
       title = "United States Compared Cause of Death Between Alzheimers and Stroke in 2017") 
  
```

to do:
see what alt text is needed
legends and titles

